    export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST"
    export const LOGIN_USER = "LOGIN_USER"
    export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL"
    
    export const LOGOUT_USER = "LOGOUT_USER"
    export const LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL"
    
    export const REGISTER_USER = "REGISTER_USER"
    export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL"
    export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST"
    
    
    export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST"
    export const LOAD_USER = "LOAD_USER"
    export const LOAD_USER_FAIL = "LOAD_USER_FAIL"
    
    export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST"
    export const UPDATE_PROFILE = "UPDATE_PROFILE"
    export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL"
    export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET"
    
    export const ADMIN_ALL_USERS_REQUEST = "ADMIN_ALL_USERS_REQUEST"
    export const ADMIN_ALL_USERS_SUCCESS = "ADMIN_ALL_USERS_SUCCESS"
    export const ADMIN_ALL_USERS_FAIL = "ADMIN_ALL_USERS_FAIL"
    
    export const ADMIN_UPDATE_USERS_RESET = "ADMIN_UPDATE_USERS_RESET"
    export const ADMIN_UPDATE_USERS_FAIL = "ADMIN_UPDATE_USERS_FAIL" 
    export const ADMIN_UPDATE_USERS_REQUEST = "ADMIN_UPDATE_USERS_REQUEST"
    export const ADMIN_UPDATE_USERS_SUCCESS = "ADMIN_UPDATE_USERS_SUCCESS"
    
    export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST"
    export const USER_DETAILS = "USER_DETAILS"
    export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL"



//// CONSTANTS FOR ROOMS

    export const ADD_NEW_ROOM_REQUEST = "ADD_NEW_ROOM_REQUEST" 
    export const ADD_NEW_ROOM_SUCCESS = "ADD_NEW_ROOM_SUCCESS"
    export const ADD_NEW_ROOM_Fail = "ADD_NEW_ROOM_Fail"
    export const ADD_NEW_ROOM_RESET = "ADD_NEW_ROOM_RESET"


    export const GET_ALL_ROOM_REQUEST = "GET_ALL_ROOM_REQUEST" 
    export const GET_ALL_ROOM_SUCCESS = "GET_ALL_ROOM_SUCCESS"
    export const GET_ALL_ROOM_Fail = "GET_ALL_ROOM_Fail"

    export const GET_ALL_ROOM_PER_MANAGER_REQUEST = "GET_ALL_ROOM_REQUEST" 
    export const GET_ALL_ROOM_PER_MANAGER_SUCCESS = "GET_ALL_ROOM_SUCCESS"
    export const GET_ALL_ROOM_PER_MANAGER_Fail = "GET_ALL_ROOM_Fail"

    export const UPDATE_ROOM_REQUEST = "UPDATE_ROOM_REQUEST" 
    export const UPDATE_ROOM_SUCCESS = "UPDATE_ROOM_SUCCESS"
    export const UPDATE_ROOM_Fail = "UPDATE_ROOM_Fail"
    export const UPDATE_ROOM_RESET = "UPDATE_ROOM_RESET"


    export const DELETE_ROOM_REQUEST = "DELETE_ROOM_REQUEST" 
    export const DELETE_ROOM_SUCCESS = "DELETE_ROOM_SUCCESS"
    export const DELETE_ROOM_Fail = "DELETE_ROOM_Fail"
    export const DELETE_ROOM_RESET = "DELETE_ROOM_RESET"


    //// CONSTANTS FOR BOOKING

    //// DeleteBooking
    export const NEW_BOOKING_REQUEST = "NEW_BOOKING_REQUEST" 
    export const NEW_BOOKING_SUCCESS = "NEW_BOOKING_SUCCESS" 
    export const NEW_BOOKING_FAIL = "NEW_BOOKING_FAIL" 



    export const ALL_BOOKING_REQUEST = "ALL_BOOKING_REQUEST" 
    export const ALL_BOOKING_SUCCESS = "ALL_BOOKING_SUCCESS" 
    export const ALL_BOOKING_FAIL = "ALL_BOOKING_FAIL" 


    export const DELETE_BOOKING_REQUEST = "DELETE_BOOKING_REQUEST" 
    export const DELETE_BOOKING_SUCCESS = "DELETE_BOOKING_SUCCESS" 
    export const DELETE_BOOKING_FAIL = "DELETE_BOOKING_FAIL" 
    